import { useState, useEffect, useRef } from "react";
import { useQuery, useMutation } from "@tanstack/react-query";
import { nanoid } from "nanoid";
import { apiRequest } from "@/lib/queryClient";
import { Message } from "@shared/schema";
import ChatMessage from "./chat-message";
import ChatInput from "./chat-input";
import { Loader } from "@/components/ui/loader";
import { Separator } from "@/components/ui/separator";

interface ChatInterfaceProps {
  chatbotSlug: string;
  isPreview?: boolean;
  previewSystemPrompt?: string;
}

interface ChatbotPublicInfo {
  id: number;
  name: string;
  description: string;
  model: string;
  welcomeMessage?: string;
  welcomeMessages?: string[];
  suggestedQuestions?: string[];
}

interface ChatResponse {
  message: Message;
  sessionId: string;
}

export default function ChatInterface({ chatbotSlug, isPreview = false, previewSystemPrompt }: ChatInterfaceProps) {
  const [sessionId, setSessionId] = useState<string>("");
  const [messages, setMessages] = useState<Message[]>([]);
  const [inputDisabled, setInputDisabled] = useState(false);
  const [showSuggestions, setShowSuggestions] = useState(true);
  const messagesEndRef = useRef<HTMLDivElement>(null);

  // Get chatbot information
  const { data: chatbotInfo, isLoading: isLoadingChatbot, error: chatbotError } = useQuery<ChatbotPublicInfo>({
    queryKey: [`/api/public/chatbot/${chatbotSlug}`],
    enabled: !isPreview && !!chatbotSlug,
  });

  // Load previous messages if sessionId exists
  const { data: previousMessages } = useQuery<Message[]>({
    queryKey: [`/api/public/chatbot/${chatbotSlug}/messages/${sessionId}`],
    enabled: !isPreview && !!sessionId && !!chatbotSlug,
  });

  // Message sending mutation
  const messageMutation = useMutation({
    mutationFn: async (message: string) => {
      if (isPreview) {
        try {
          // Make a direct call to OpenAI for preview mode
          const response = await apiRequest(
            "POST",
            "/api/preview/generate-response",
            { 
              message,
              systemPrompt: previewSystemPrompt || "You are a helpful AI assistant that responds to users in a friendly and informative way."
            }
          );
          const data = await response.json();
          
          return {
            message: {
              id: Date.now(),
              chatbotId: 0,
              sessionId: "preview",
              isUser: false,
              content: data.response,
              timestamp: new Date(),
            },
            sessionId: "preview"
          } as ChatResponse;
        } catch (error) {
          // Fallback if the API call fails
          return {
            message: {
              id: Date.now(),
              chatbotId: 0,
              sessionId: "preview",
              isUser: false,
              content: "I couldn't generate a response. This is a preview of your chatbot configuration. In the deployed version, responses will be generated by OpenAI.",
              timestamp: new Date(),
            },
            sessionId: "preview"
          } as ChatResponse;
        }
      } else {
        const response = await apiRequest(
          "POST", 
          `/api/public/chatbot/${chatbotSlug}/messages`, 
          { message, sessionId }
        );
        return await response.json();
      }
    },
    onSuccess: (data: ChatResponse) => {
      if (!sessionId) {
        setSessionId(data.sessionId);
      }
    },
    onError: (error) => {
      // Add error message to chat
      setMessages(prev => [
        ...prev,
        {
          id: Date.now(),
          chatbotId: 0,
          sessionId: sessionId || "error",
          isUser: false,
          content: "Sorry, there was an error processing your message. Please try again.",
          timestamp: new Date(),
        }
      ]);
    },
    onSettled: () => {
      setInputDisabled(false);
    }
  });

  // Initialize session on first load
  useEffect(() => {
    if (!isPreview && !sessionId) {
      setSessionId(nanoid());
    }
  }, [isPreview, sessionId]);

  // Update messages when previousMessages changes
  useEffect(() => {
    if (previousMessages && previousMessages.length > 0) {
      setMessages(previousMessages);
      // If there are previous messages, don't show suggestions
      setShowSuggestions(false);
    }
  }, [previousMessages]);

  // Add welcome message
  useEffect(() => {
    if (messages.length === 0) {
      if (isPreview) {
        // Default preview welcome messages (multiple in sequence)
        const previewMessages = [
          "Hello! I'm your chatbot assistant.",
          "I can help answer questions about your topic.",
          "Feel free to ask me anything!"
        ];
        
        const welcomeMessages = previewMessages.map((message, index) => ({
          id: index,
          chatbotId: 0,
          sessionId: "preview",
          isUser: false,
          content: message,
          timestamp: new Date(Date.now() + index * 100), // Slight timestamp difference to maintain order
        }));
        
        setMessages(welcomeMessages);
      } else {
        // Use all welcome messages in sequence
        if (chatbotInfo?.welcomeMessages && chatbotInfo.welcomeMessages.length > 0) {
          // Create an array of welcome messages
          const welcomeMessages = chatbotInfo.welcomeMessages.map((message, index) => ({
            id: index,
            chatbotId: chatbotInfo?.id || 0,
            sessionId: sessionId || "initial",
            isUser: false,
            content: message,
            timestamp: new Date(Date.now() + index * 100), // Slight timestamp difference to maintain order
          }));
          
          setMessages(welcomeMessages);
        } 
        // Fall back to single welcomeMessage if welcomeMessages isn't available
        else if (chatbotInfo?.welcomeMessage) {
          setMessages([
            {
              id: 0,
              chatbotId: chatbotInfo?.id || 0,
              sessionId: sessionId || "initial",
              isUser: false,
              content: chatbotInfo.welcomeMessage,
              timestamp: new Date(),
            }
          ]);
        } 
        // Default fallback
        else {
          setMessages([
            {
              id: 0,
              chatbotId: chatbotInfo?.id || 0,
              sessionId: sessionId || "initial",
              isUser: false,
              content: "Hello! How can I assist you today?",
              timestamp: new Date(),
            }
          ]);
        }
      }
    }
  }, [isPreview, messages.length, chatbotInfo, sessionId]);

  // Scroll to bottom when messages change
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSendMessage = async (message: string) => {
    if (!message.trim() || inputDisabled) return;
    
    // Add user message to UI immediately
    const userMessage: Message = {
      id: Date.now(),
      chatbotId: chatbotInfo?.id || 0,
      sessionId: sessionId || "preview",
      isUser: true,
      content: message,
      timestamp: new Date(),
    };
    
    setMessages(prev => [...prev, userMessage]);
    setInputDisabled(true);
    
    // Hide suggestions after the first message is sent
    setShowSuggestions(false);
    
    try {
      const response = await messageMutation.mutateAsync(message);
      setMessages(prev => [...prev, response.message]);
    } catch (error) {
      // Error is handled in the mutation
    }
  };
  
  const handleSuggestedQuestionClick = (question: string) => {
    if (inputDisabled) return;
    handleSendMessage(question);
  };

  if (!isPreview && isLoadingChatbot) {
    return (
      <div className="flex items-center justify-center h-full">
        <Loader size="lg" withText text="Loading chatbot..." />
      </div>
    );
  }

  if (!isPreview && chatbotError) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-4 text-center">
        <h3 className="text-lg font-semibold text-red-500 mb-2">Chatbot not found</h3>
        <p className="text-neutral-400">The chatbot you're looking for doesn't exist or has been removed.</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col h-full overflow-hidden bg-white rounded-lg shadow border border-gray-200">
      {/* Chat Header */}
      <div className="bg-gradient-to-r from-pink-100 to-blue-100 p-3 flex items-center justify-between">
        <div className="flex items-center">
          <div className="bg-pink-200 p-2 rounded-full mr-3">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="text-pink-500">
              <path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"></path>
            </svg>
          </div>
          <div>
            <h2 className="font-semibold text-gray-800 text-lg">
              {isPreview ? "Chatbot Preview" : chatbotInfo?.name}
            </h2>
            {!isPreview && chatbotInfo?.description && (
              <p className="text-sm text-gray-600">{chatbotInfo.description}</p>
            )}
          </div>
        </div>
        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-cyan-100 text-cyan-800">
          <span className="w-2 h-2 bg-cyan-400 rounded-full mr-1.5"></span>
          Online
        </span>
      </div>

      {/* Chat Messages */}
      <div className="flex-1 overflow-y-auto p-4 space-y-4 custom-scrollbar">
        {messages.map((message) => (
          <ChatMessage 
            key={message.id} 
            message={message} 
            chatbotName={chatbotInfo?.name}
          />
        ))}
        <div ref={messagesEndRef} />
        
        {/* Loading indicator for response */}
        {inputDisabled && messageMutation.isPending && (
          <div className="flex items-start">
            <div className="flex-shrink-0 bg-pink-100 w-8 h-8 rounded-full flex items-center justify-center">
              <svg className="animate-pulse w-5 h-5 text-pink-500" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
              </svg>
            </div>
            <div className="ml-3 bg-gray-100 rounded-lg py-2 px-4">
              <div className="flex space-x-2">
                <div className="w-2 h-2 rounded-full bg-pink-400 animate-bounce" style={{ animationDelay: "0ms" }}></div>
                <div className="w-2 h-2 rounded-full bg-pink-400 animate-bounce" style={{ animationDelay: "150ms" }}></div>
                <div className="w-2 h-2 rounded-full bg-pink-400 animate-bounce" style={{ animationDelay: "300ms" }}></div>
              </div>
            </div>
          </div>
        )}
      </div>
      
      {/* Suggested Questions Section */}
      {showSuggestions && 
        (!isPreview ? 
          (chatbotInfo?.suggestedQuestions && chatbotInfo.suggestedQuestions.length > 0) : 
          isPreview) && (
        <div className="px-4 py-3 border-t border-gray-200 bg-gray-50">
          <p className="text-sm font-medium text-pink-500 mb-2 flex items-center">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" className="mr-1"><path d="M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10"/></svg>
            Suggested questions:
          </p>
          <div className="flex flex-wrap gap-2">
            {isPreview ? (
              // Show sample suggested questions in preview mode
              <>
                <button 
                  onClick={() => handleSuggestedQuestionClick("How long is my surgery going to take?")}
                  className="px-3 py-1.5 text-sm bg-white hover:bg-gray-100 text-gray-800 rounded-full border border-gray-300 transition-colors shadow-sm"
                >
                  How long is my surgery going to take?
                </button>
                <button 
                  onClick={() => handleSuggestedQuestionClick("Tell me about the MAKO Robotic Technique")}
                  className="px-3 py-1.5 text-sm bg-white hover:bg-gray-100 text-gray-800 rounded-full border border-gray-300 transition-colors shadow-sm"
                >
                  Tell me about the MAKO Robotic Technique
                </button>
                <button 
                  onClick={() => handleSuggestedQuestionClick("Why do I need dental clearance?")}
                  className="px-3 py-1.5 text-sm bg-white hover:bg-gray-100 text-gray-800 rounded-full border border-gray-300 transition-colors shadow-sm"
                >
                  Why do I need dental clearance?
                </button>
              </>
            ) : (
              // Show actual suggested questions from the chatbot
              chatbotInfo?.suggestedQuestions?.map((question, index) => (
                <button 
                  key={index}
                  onClick={() => handleSuggestedQuestionClick(question)}
                  className="px-3 py-1.5 text-sm bg-white hover:bg-gray-100 text-gray-800 rounded-full border border-gray-300 transition-colors shadow-sm"
                >
                  {question}
                </button>
              ))
            )}
          </div>
        </div>
      )}
      
      {/* Chat Input */}
      <div className="p-4 border-t border-gray-200 bg-white">
        <ChatInput 
          onSendMessage={handleSendMessage} 
          disabled={inputDisabled} 
        />
        
        <div className="mt-3 text-center">
          <p className="text-xs text-gray-500">
            Powered by Aidify | AI-powered assistance
          </p>
        </div>
      </div>
    </div>
  );
}
